#!/bin/bash

if [ -e /sys/fs/cgroup/systemd ]; then
    case "$2" in
        up)
            systemctl start automountnfs.service
        ;;
        down)
            systemctl stop automountnfs.service
        ;;
        esac
fi
